server:
  port: 9002

spring:
  application:
    name: cloud-user-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/dataview?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 310310




mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: top.kissvs.dataview.entities    # 所有Entity别名类所在包


